@issuer-server
Feature: Issuer Routes
  In order manage directory
  As a QA Automation
  I want to make sure CRUD operations through REST API works fine

  Scenario Outline: Validate the certificate generated by the issuer and send it to mouro to be saved.
    Given A account <request>
    When I send POST request to /issuer/issueCertificate
    Then I get response code 200

    Examples:
      | request                                              |
      | {"jwt":"gaston.genaud@didi.org.ar","sendPush":true } |

  Scenario Outline: Generate a shareRequest and send it via mouro for the user to send the information
    Given A token <request>
    When I send POST request to /issuer/issueShareRequest
    Then I get response code 200

    Examples:
      | request                     |
      | {"did": "sd", "jwt": "test"}|


  Scenario Outline: Allows you to revoke a certificate previously stored in mouro.
    Given A account <request>
    When I send POST request to /issuer/revokeCertificate
    Then I get response code 200

    Examples:
      | request                                                                            |
      | {"did": "gaston.genaud@didi.org.ar", "sub": "123456aaAA", "jwt":"20", "hash":"20"} |

  Scenario Outline: Allows you to validate a certificate from the jwt.
    Given A account <request>
    When I send POST request to /issuer/verifyCertificate
    Then I get response code 200

    Examples:
      | request         |
      | {"jwt": "2103"} |

  Scenario Outline: Verify the existence of the issuer according to the did.
    Given A account <request>
    When I send POST request to /issuer/verify
    Then I get response code 200

    Examples:
      | request              |
      | {"did":"didexample"} |

  Scenario Outline: Verify the existence of the issuer according to the did.
    Given A account <request>
    When I send POST request to /issuer/verify
    Then I get response code 200

    Examples:
      | request                                |
      | {"did":"didexample", "name": "Gaston"} |

  Scenario Outline: Authorize an Issuer to emit with DIDI
    Given A did and random name request
    When I send POST request to /issuer
    Then I get response code 200 and status success
    
#Endpoints pendientes
# *   /issuer/:{did}/refresh:
#  *   /issuer/:{did}:
# *   /issuer/:{did}:
